server.port=8075
server.servlet.context-path=/CFM/v1

spring.application.name=chitfund


security.jwt.token.secret-key=chitfund
security.jwt.token.expire-length=86400000


spring.profiles.active=dev


spring.datasource.url=jdbc:postgresql://localhost:5432/chitfund
spring.datasource.username=postgres
spring.datasource.password=Chethan@123


app.api.swagger.enable=true

spring.jpa.hibernate.ddl-auto=update




